version: "3.7"

services:
    node:
        image: node:12-alpine
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app

networks:
    default:
        external: true
        name: neat-frontend